stages:
  - install
  - test
  - deploy

variables:
  VENV_DIR: ".venv"

before_script:
  - python3 -m venv $VENV_DIR
  - source $VENV_DIR/bin/activate
  - pip install -r requirements.txt

install:
  stage: install
  script:
    - echo "Installation des dépendances terminée."

test:
  stage: test
  script:
    - pytest tests/
  artifacts:
    when: always
    paths:
      - report/

deploy:
  stage: deploy
  script:
    - uvicorn src.api.app:app --host 0.0.0.0 --port 8000
