version: '3.8'

services:
  api:
    build: .
    container_name: api_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: .
    container_name: frontend_service
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run src/frontend/app_gradio.py --server.port 8501 --server.address 0.0.0.0
