version: "3.8"

services:
  backend:
    build:
      context: ./src/api
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./src/frontend
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
